//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GonHuoSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressBiao
    {
        public int Aid { get; set; }
        public string AName { get; set; }
        public int Gid { get; set; }
        public string Aphone { get; set; }
        public string AAddress { get; set; }
        public System.DateTime TTime { get; set; }
        public System.DateTime XTime { get; set; }
        public int ZhuangTai { get; set; }
    }
}
