//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GonHuoSModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GonhuoShang
    {
        public int Gid { get; set; }
        public string GName { get; set; }
        public int GType { get; set; }
        public string Email { get; set; }
        public int Youbian { get; set; }
        public string Phone { get; set; }
        public string GAddress { get; set; }
        public System.DateTime TTime { get; set; }
        public System.DateTime XTime { get; set; }
        public int ZhuangTai { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
